### ISSUE TITLE
IRIS FHIR Template README is outdated.

### ISSUE THREAD

**Issue by legkvla** [intersystems-community/fhir-bugreports#1]
https://github.com/intersystems-community/iris-fhir-template?tab=readme-ov-file#how-to-start-development

> Open /src/cls/PackageSample/ObjectScript.cls class and try to make changes - it will be compiled in running IRIS docker container.

These file and package are not exist in this repo/template. Video gif is oudated too.

**Comment by evshvarov** [comment]
Fixed. Thank you!
